export const siteConfig = {
  name: "Ecotech Recyclers",
  fullName: "Ecotech Recyclers (OPC) Pvt. Ltd.",
  tagline: "Waste to Worth",
  url: "https://ecotechrecyclers.in",
  description:
    "Ecotech Recyclers — India's trusted e-waste and scrap recycling company. DPIIT-recognized startup offering door-to-door collection, precious metal recovery, and industrial scrap processing. Waste to Worth.",
  keywords: [
    "e-waste recycling India",
    "scrap recycling company",
    "precious metal recovery",
    "electronic waste disposal",
    "copper scrap buyer",
    "gold silver scrap",
    "platinum palladium recovery",
    "DPIIT startup recycling",
    "industrial scrap buyer India",
    "e-waste pickup Delhi",
    "ecotech recyclers",
    "scrap dealer India",
    "environmental recycling company",
    "ewaste management",
  ],
  ogImage: "/og-image.jpg",
  twitterHandle: "@ecotechrecycles",
  locale: "en_IN",
  themeColor: {
    light: "#ffffff",
    dark: "#0d1f0f",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "About", href: "#about" },
    { label: "Services", href: "#services" },
    { label: "Materials", href: "#materials" },
    { label: "Process", href: "#process" },
    { label: "Contact", href: "#contact" },
  ],
  social: [
    { platform: "LinkedIn", href: "https://linkedin.com", icon: "linkedin" },
    { platform: "Twitter", href: "https://twitter.com", icon: "twitter" },
    { platform: "WhatsApp", href: "https://wa.me/91XXXXXXXXXX", icon: "whatsapp" },
  ],
  footer: {
    copyright: "© 2026 Ecotech Recyclers (OPC) Pvt. Ltd. All rights reserved.",
    cin: "CIN: U38200UP2026OPC000000",
    gstin: "GSTIN: Applied",
  },
};
